/* ============================================================
   JEOPARDY GAME CONFIG
   ============================================================
   Edit this file to change the game. That's it — no other file
   needs touching.

   Structure:
   - title: shown at the top of the board
   - categories: exactly 5, each with a name and 5 clues
   - Each clue has:
       question : what the host reads / players see
       answer   : revealed when the host clicks "Reveal Answer"
       image    : (OPTIONAL) path or URL to a picture shown with
                  the question — great for "guess what this is"
                  style clues. Put local images in the images/
                  folder, e.g.  image: "images/my-picture.png"
   - Point values are automatic: 100, 200, 300, 400, 500
     (row 1 = 100 ... row 5 = 500). Change POINT_VALUES below
     if you want different stakes.
   ============================================================ */

const GAME_CONFIG = {
  title: "MEGA JEOPARDY",

  categories: [
    {
      name: "AI Agents",
      clues: [
        {
          question: "This is the general term for an AI system that can plan, use tools, and take actions autonomously to achieve a goal.",
          answer: "What is an (AI) agent?",
        },
        {
          question: "MCP, a popular open protocol for connecting AI agents to tools and data, stands for this.",
          answer: "What is the Model Context Protocol?",
        },
        {
          question: "This is the name for the loop where an agent reasons about what to do, calls a tool, observes the result, and repeats.",
          answer: "What is the ReAct loop (reason + act)?",
        },
        {
          question: "When multiple agents divide up a task and coordinate with each other, this is the general term for such a system.",
          answer: "What is a multi-agent system?",
        },
        {
          question: "This safety concern describes an agent finding an unintended shortcut that maximizes its objective while violating the spirit of the task.",
          answer: "What is reward hacking (specification gaming)?",
        },
      ],
    },
    {
      name: "Spot the Slop",
      clues: [
        {
          question: "AI-generated images of people notoriously struggle to draw the right number of these body parts.",
          answer: "What are fingers?",
        },
        {
          question: "Look closely at this picture — name one clue that it was generated by AI.",
          answer: "Sample answers: garbled text, melted background objects, inconsistent lighting, extra limbs.",
          image: "images/sample-slop.svg",
        },
        {
          question: "This word — also used for low-grade food waste fed to pigs — became the go-to term for low-effort AI-generated content flooding the internet.",
          answer: "What is slop?",
        },
        {
          question: "AI-written text loves this em-dash-adjacent crutch phrase: \"It's not just X — it's Y.\" Name the general term for such telltale AI writing patterns.",
          answer: "What are AI tells (or 'GPT-isms')?",
        },
        {
          question: "This term describes an AI confidently stating false information as if it were fact.",
          answer: "What is a hallucination?",
        },
      ],
    },
    {
      name: "World Cup",
      clues: [
        {
          question: "This country has won the most FIFA World Cups, with five titles.",
          answer: "What is Brazil?",
        },
        {
          question: "The 2026 World Cup is co-hosted by these three countries.",
          answer: "What are the USA, Canada, and Mexico?",
        },
        {
          question: "This Argentine legend finally lifted the World Cup trophy in 2022 in Qatar.",
          answer: "Who is Lionel Messi?",
        },
        {
          question: "In the 2014 semi-final, Germany humiliated host nation Brazil with this infamous scoreline.",
          answer: "What is 7–1?",
        },
        {
          question: "This player scored a hat-trick in the 2022 World Cup final — and still lost.",
          answer: "Who is Kylian Mbappé?",
        },
      ],
    },
    {
      name: "Hallucination Station",
      clues: [
        {
          question: "TRUE or FALSE: An AI once advised a lawyer with court cases that turned out to be completely made up.",
          answer: "TRUE — in 2023 a lawyer submitted a brief citing six non-existent cases invented by ChatGPT.",
        },
        {
          question: "One of these three 'facts' is real, the other two are hallucinated: (a) The Eiffel Tower grows taller in summer, (b) Goldfish have a 3-second memory, (c) Napoleon was unusually short.",
          answer: "What is (a)? Heat expands the metal by ~15 cm. The other two are myths.",
        },
        {
          question: "This is the common technique of grounding an AI's answers in retrieved documents to reduce hallucinations — abbreviated RAG.",
          answer: "What is Retrieval-Augmented Generation?",
        },
        {
          question: "When an AI invents a plausible-looking citation, URL, or API function that doesn't exist, researchers call this type of output by this confident-sounding word.",
          answer: "What is a confabulation (also accepted: fabrication / hallucination)?",
        },
        {
          question: "Asking a model to say 'I don't know' instead of guessing, or sampling multiple answers and checking agreement, are strategies to improve this property of AI outputs.",
          answer: "What is factuality (truthfulness / calibration)?",
        },
      ],
    },
    {
      name: "Prompt Like a Pro",
      clues: [
        {
          question: "This is the term for the initial hidden instructions that define an AI assistant's behavior before the user says anything.",
          answer: "What is a system prompt?",
        },
        {
          question: "Giving the model a few worked examples in the prompt before asking your real question is called this kind of prompting.",
          answer: "What is few-shot prompting?",
        },
        {
          question: "\"Let's think step by step\" is the classic incantation for this prompting technique.",
          answer: "What is chain-of-thought prompting?",
        },
        {
          question: "This attack tries to override an AI's instructions by smuggling malicious commands into the content it processes.",
          answer: "What is prompt injection?",
        },
        {
          question: "This is the term for the maximum amount of text (measured in tokens) a model can consider at once.",
          answer: "What is the context window?",
        },
      ],
    },
  ],
};

/* Point values per row (top to bottom). */
const POINT_VALUES = [100, 200, 300, 400, 500];
